#!/bin/sh
# postrm script for sphinx

set -e

SPHINXUSER=sphinx

case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
		if getent passwd $SPHINXUSER > /dev/null 2>/dev/null; then
			deluser --system $SPHINXUSER
		fi
    ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
