#!/bin/sh
# postinst script for sphinx

set -e

SPHINXUSER=sphinx

case "$1" in
    configure)
		getent passwd $SPHINXUSER > /dev/null 2>/dev/null || adduser --no-create-home --system $SPHINXUSER
    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
