Document: sphinx
Title: Debian sphinx Manual
Author: <insert document author here>
Abstract: This manual describes what sphinx is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sphinx/sphinx.sgml.gz

Format: postscript
Files: /usr/share/doc/sphinx/sphinx.ps.gz

Format: text
Files: /usr/share/doc/sphinx/sphinx.text.gz

Format: HTML
Index: /usr/share/doc/sphinx/html/index.html
Files: /usr/share/doc/sphinx/html/*.html

  
